### ISSUE TITLE
CocoaPods search api not working

### ISSUE THREAD

**Issue by mohammadkalim** [CocoaPods/guides.cocoapods.org#156] opened 2018-04-01 12:21 UTC
Hello,

Cocoapods search api is not working i check in the inspect element. Please look up this serious issue and resolve it as soon as possible Thanking in advance.

https://aws-search.cocoapods.org/api/v1/pods.picky.hash.json?query=s&ids=20&offset=0&sort=quality

**Screenshot**: https://www.dropbox.com/s/0dc7tqu7uf0ecxn/Screenshot%202018-04-01%2001.47.15.png?dl=0

**Comment by orta** [comment] 2018-04-01 12:32
Dupe of https://github.com/CocoaPods/cocoapods.org/issues/351

**Closed by orta** 2018-04-01 12:32 UTC
